name: Generate Random Numbers

on:
  push:
    branches:
      - main  # Change this to match your main branch name

jobs:
  generate_numbers_job:
    name: Generate Numbers
    runs-on: self-hosted



    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # - name: Set up Python 
    #   uses: actions/setup-python@v2
     

    # - name: Install dependencies
    #   run: pip install -r hello.txt  

    - name: Run Python Script
      run: python demo.py 

  additional_job:
    name: Additional Job
    runs-on: self-hosted

   

    env:
      ENV_VARIABLE: "hello"  

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

   
    # - name: Set up Python 
    #   uses: actions/setup-python@v2
     

    - name: Print Environment Variable
      run: echo "$ENV_VARIABLE" 

  secret_job:
    needs: additional_job 
    runs-on: self-hosted
    if: ${{always()}}
   

    env:
      secret: ${{secrets.Password}}  

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

     

    - name: Print secret
      run: echo "$secret" 
